<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="/styles/index.css">
</head>
    <body>
        <div class="container">
            <aside class="aside-container">
                <ul>
                    <button class="btn-create">Criar uma comunidade</button>
                    <li>
                        <i class="fa-solid fa-house"></i>
                        Home
                    </li>
                </ul>
            </aside>
            <main>
                <h2>Oops... Parece que não existe nenhuma comunidade encontrada.</h2>
                <button class="btn-create">Criar uma comunidade</button>
            </main>
        </div>
    </body>
</html>