<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/styles/styles.css">
    <script src="https://kit.fontawesome.com/eb4a288377.js" crossorigin="anonymous"></script>
    <title>DevForum - Crie tópicos</title>
</head>
<body>
    <header>
        <h1>DevFórum</h1>
        <div class="search-container">
            <i class="fa-solid fa-magnifying-glass"></i>
            <input type="text" placeholder="Pesquise...">
        </div>
        <button><a href="/acessar">Acessar</a></button>
    </header>
    <?= $this->content() ?>
</body>
</html>